version: '3.8'

services:
  web:
    image: pot-system-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pot_system_app
    restart: always
    ports:
      - "5001:8080" # Ánh xạ cổng 5001 trên VPS để không đụng độ với dự án tiếng Anh (5000)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Cần thiết để gọi về SQL Server trên VPS
